In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [7]:
df = pd.read_csv('Divar.csv')
display(df.head(15))
display(df.info())
display(df.describe())

C:\Users\Ramtin\AppData\Local\Temp\ipykernel_12844\1894331024.py:1: DtypeWarning: Columns (0: rent_to_single, 1: floor, 2: total_floors_count, 3: extra_person_capacity) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Divar.csv')

,Unnamed: 0,cat2_slug,cat3_slug,city_slug,neighborhood_slug,created_at_month,user_type,description,title,rent_mode,...,property_type,regular_person_capacity,extra_person_capacity,cost_per_extra_person,rent_price_on_regular_days,rent_price_on_special_days,rent_price_at_weekends,location_latitude,location_longitude,location_radius
0,0,temporary-rent,villa,karaj,mehrshahr,2024-08-01 00:00:00,مشاور املاک,۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...,باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه,NaN,...,NaN,4.0,6,350000.0,1500000.0,3.500000e+09,3500000.0,35.811684,50.936600,500.0
1,1,residential-sell,apartment-sell,tehran,gholhak,2024-05-01 00:00:00,مشاور املاک,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...,۶۰ متر قلهک فول امکانات,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.0
2,2,residential-rent,apartment-rent,tehran,tohid,2024-10-01 00:00:00,NaN,تخلیه پایان ماه,آپارتمان ۳ خوابه ۱۳۲ متر,مقطوع,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.703865,51.373459,NaN
3,3,commercial-rent,office-rent,tehran,elahiyeh,2024-06-01 00:00:00,NaN,فرشته تاپ لوکیشن\n۹۰ متر موقعیت اداری\nیک اتاق...,فرشته ۹۰ متر دفتر کار مدرن موقعیت اداری,مقطوع,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,residential-sell,apartment-sell,mashhad,emamreza,2024-05-01 00:00:00,مشاور املاک,هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...,۱۱۵ متری/شمالی رو به آفتاب/اکبری,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,residential-rent,apartment-rent,ahvaz,mellirah,2024-09-01 00:00:00,NaN,اپارتمان ۱۰۰متری واحد جلو دارای دو اتاق خواب ک...,اپارتمان ۱۰۰متری ملی راه واحد جلو,مقطوع,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,commercial-rent,office-rent,kermanshah,NaN,2024-11-01 00:00:00,NaN,♦مشاورین املاک سیب♦\n✅️کد:G۱۰۵\n♦با سالها سابق...,واحداداری ۸۰متری ۲۲بهمن(برق),مقطوع,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,residential-sell,apartment-sell,tehran,dardasht,2024-09-01 00:00:00,مشاور املاک,♡♡♡♡♡♡بنام خدا♡♡♡♡♡♡\n♡♡♡عرض ادب واحترام♡♡♡\n♡...,اپارتمان ۱۰۰متری طبقه۳و۴ فول دردشت شمالی,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.729832,51.505466,500.0
8,8,residential-sell,apartment-sell,mahdasht-city,NaN,2024-06-01 00:00:00,مشاور املاک,با سلام\n\nاملاک بزرگ اتحاد با ۲شعبه فعال با ف...,۷۸متری دوبحرنورگیر بازسازی شده شیک سندتک برگ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.712364,50.794781,500.0
9,9,residential-sell,apartment-sell,mashhad,faramarzabbasi,2024-10-01 00:00:00,NaN,اول رسالت فرد نزدیک به حاشیه فرامرز .. ساکنین...,متراژ ۸۰ متر فرامرز نزدیک حاشیه,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,residential-sell,apartment-sell,pardis-city,NaN,2024-11-01 00:00:00,NaN,سردرب عالی \nویو عالی بدون مشرف \nنصبیات نصب ش...,فاز ۱۱ زون ۲ ساخت شرکت کوزو ترکیه,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.778664,51.757549,NaN
11,11,residential-rent,apartment-rent,tehran,gisha,2024-08-01 00:00:00,مشاور املاک,‼️‼️ارزنده ترین واحد منطقه ‼️‼️ \n\n✅ 91 متر ب...,گیشا / ۹۱ متر /فرعی زوج مشرف به پارک گفتگو/ ار...,مجانی,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.733952,51.380608,500.0
12,12,residential-sell,apartment-sell,mashhad,farhang,2024-06-01 00:00:00,NaN,با سلام\n\n✨✨ شما لایق بهترین ها هستید ✨✨\n\n✅...,تاپ لوکیشن جلال سروش ۱۶۹متر کلید موجود قبل فرهنگ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,36.321831,59.524502,500.0
13,13,commercial-sell,shop-sell,foolad-shahr,NaN,2024-07-01 00:00:00,NaN,مغازه فروشی بازار هنر 16متر پاخور عالی,مغازه ب8بازار,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32.467804,51.404095,NaN
14,14,residential-sell,plot-old,ahvaz,pardis-ahvaz,2024-07-01 00:00:00,NaN,یک زمین به متراژ۵۰۰متر واقع کوی سادات خیابان چ...,زمین۵۰۰ متر,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.265947,48.568604,NaN

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 61 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   Unnamed: 0                  1000000 non-null  int64
 1   cat2_slug                   1000000 non-null  str
 2   cat3_slug                   999999 non-null   str
 3   city_slug                   999998 non-null   str
 4   neighborhood_slug           437139 non-null   str
 5   created_at_month            1000000 non-null  str
 6   user_type                   288882 non-null   str
 7   description                 1000000 non-null  str
 8   title                       999946 non-null   str
 9   rent_mode                   352994 non-null   str
 10  rent_value                  351322 non-null   float64
 11  rent_to_single              19 non-null       object
 12  rent_type                   103961 non-null   str
 13  price_mode                  573606 non-null   str
 14  price_value                 568346 non-null   float64
 15  credit_mode                 352994 non-null   str
 16  credit_value                352095 non-null   float64
 17  rent_credit_transform       352985 non-null   object
 18  transformable_price         352894 non-null   object
 19  transformable_credit        352085 non-null   float64
 20  transformed_credit          72409 non-null    float64
 21  transformable_rent          351248 non-null   float64
 22  transformed_rent            72409 non-null    float64
 23  land_size                   186396 non-null   float64
 24  building_size               980394 non-null   float64
 25  deed_type                   253458 non-null   str
 26  has_business_deed           34679 non-null    object
 27  floor                       541748 non-null   object
 28  rooms_count                 845899 non-null   str
 29  total_floors_count          304352 non-null   object
 30  unit_per_floor              302283 non-null   str
 31  has_balcony                 506411 non-null   object
 32  has_elevator                541749 non-null   object
 33  has_warehouse               728155 non-null   object
 34  has_parking                 728156 non-null   object
 35  construction_year           815828 non-null   str
 36  is_rebuilt                  529470 non-null   object
 37  has_water                   33444 non-null    object
 38  has_warm_water_provider     379500 non-null   str
 39  has_electricity             33445 non-null    object
 40  has_gas                     33430 non-null    object
 41  has_heating_system          368969 non-null   str
 42  has_cooling_system          350619 non-null   str
 43  has_restroom                406913 non-null   str
 44  has_security_guard          31312 non-null    object
 45  has_barbecue                31198 non-null    object
 46  building_direction          323923 non-null   str
 47  has_pool                    29390 non-null    object
 48  has_jacuzzi                 28728 non-null    object
 49  has_sauna                   28479 non-null    object
 50  floor_material              405984 non-null   str
 51  property_type               27057 non-null    str
 52  regular_person_capacity     29870 non-null    float64
 53  extra_person_capacity       24009 non-null    object
 54  cost_per_extra_person       10241 non-null    float64
 55  rent_price_on_regular_days  18068 non-null    float64
 56  rent_price_on_special_days  10463 non-null    float64
 57  rent_price_at_weekends      13551 non-null    float64
 58  location_latitude           655608 non-null   float64
 59  location_longitude          655608 non-null   float64
 60  location_radius             339699 non-null   float64
dtypes: float64(17), int64(1), object(20), str(23)
memory usage: 465.4+ MB

None

,Unnamed: 0,rent_value,price_value,credit_value,transformable_credit,transformed_credit,transformable_rent,transformed_rent,land_size,building_size,regular_person_capacity,cost_per_extra_person,rent_price_on_regular_days,rent_price_on_special_days,rent_price_at_weekends,location_latitude,location_longitude,location_radius
count,1000000.000000,3.513220e+05,5.683460e+05,3.520950e+05,3.520850e+05,7.240900e+04,3.512480e+05,7.240900e+04,1.863960e+05,9.803940e+05,29870.000000,1.024100e+04,1.806800e+04,1.046300e+04,1.355100e+04,655608.000000,655608.000000,339699.000000
mean,499999.500000,4.102299e+10,1.736537e+10,4.872084e+10,4.872222e+10,8.557025e+09,4.103164e+10,1.619934e+07,4.165480e+03,4.440648e+03,6.557650,1.209785e+10,1.389016e+11,2.355548e+10,3.156551e+10,34.982108,51.629743,465.149147
std,288675.278932,3.807534e+12,5.878739e+11,4.341346e+12,4.341407e+12,2.064576e+12,3.807935e+12,5.217890e+07,1.218927e+05,1.367118e+05,7.698655,1.103482e+12,7.042335e+12,1.542049e+12,2.434942e+12,2.379169,3.160920,125.896250
min,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,23.626478,40.162369,0.000000
25%,249999.750000,1.111110e+05,1.400000e+09,1.000000e+08,1.000000e+08,2.000000e+08,1.111110e+05,1.000000e+06,1.100000e+02,7.500000e+01,3.000000,5.000000e+04,4.000000e+05,6.000000e+05,5.500000e+05,34.553551,50.677175,500.000000
50%,499999.500000,5.000000e+06,2.840000e+09,2.500000e+08,2.500000e+08,4.000000e+08,5.000000e+06,6.000000e+06,1.950000e+02,1.030000e+02,4.000000,1.000000e+05,8.000000e+05,1.200000e+06,1.100000e+06,35.723312,51.345791,500.000000
75%,749999.250000,1.200000e+07,5.900000e+09,5.000000e+08,5.000000e+08,8.500000e+08,1.200000e+07,1.500000e+07,2.800000e+02,1.650000e+02,7.000000,2.000000e+05,1.600000e+06,2.500000e+06,2.500000e+06,36.307013,51.805291,500.000000
max,999999.000000,1.000000e+15,1.000000e+14,1.000000e+15,1.000000e+15,5.555556e+14,1.000000e+15,3.000000e+09,1.000000e+07,1.000000e+07,50.000000,1.111111e+14,5.006007e+14,1.111111e+14,2.002503e+14,40.358055,74.511620,500.000000

In [8]:
my_columns = ['cat2_slug', 'cat3_slug', 'city_slug', 'neighborhood_slug', 'created_at_month', 'location_latitude', 'location_longitude', 'location_radius', 'property_type', 'user_type', 'title', 'description', 'regular_person_capacity', 'extra_person_capacity', 'cost_per_extra_person']
my_df = df[my_columns].copy()
print(f"Number of rows : {my_df.shape[0]:,} | Number of columns : {my_df.shape[1]}")
print('Missing values % :')
missing_percentage = my_df.isnull().mean() * 100
print(missing_percentage.round(2))
display(my_df.head())
display(my_df.describe())

Number of rows : 1,000,000 | Number of columns : 15
Missing values % :
cat2_slug                   0.00
cat3_slug                   0.00
city_slug                   0.00
neighborhood_slug          56.29
created_at_month            0.00
location_latitude          34.44
location_longitude         34.44
location_radius            66.03
property_type              97.29
user_type                  71.11
title                       0.01
description                 0.00
regular_person_capacity    97.01
extra_person_capacity      97.60
cost_per_extra_person      98.98
dtype: float64

,cat2_slug,cat3_slug,city_slug,neighborhood_slug,created_at_month,location_latitude,location_longitude,location_radius,property_type,user_type,title,description,regular_person_capacity,extra_person_capacity,cost_per_extra_person
0,temporary-rent,villa,karaj,mehrshahr,2024-08-01 00:00:00,35.811684,50.936600,500.0,NaN,مشاور املاک,باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه,۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...,4.0,6,350000.0
1,residential-sell,apartment-sell,tehran,gholhak,2024-05-01 00:00:00,NaN,NaN,500.0,NaN,مشاور املاک,۶۰ متر قلهک فول امکانات,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...,NaN,NaN,NaN
2,residential-rent,apartment-rent,tehran,tohid,2024-10-01 00:00:00,35.703865,51.373459,NaN,NaN,NaN,آپارتمان ۳ خوابه ۱۳۲ متر,تخلیه پایان ماه,NaN,NaN,NaN
3,commercial-rent,office-rent,tehran,elahiyeh,2024-06-01 00:00:00,NaN,NaN,NaN,NaN,NaN,فرشته ۹۰ متر دفتر کار مدرن موقعیت اداری,فرشته تاپ لوکیشن\n۹۰ متر موقعیت اداری\nیک اتاق...,NaN,NaN,NaN
4,residential-sell,apartment-sell,mashhad,emamreza,2024-05-01 00:00:00,NaN,NaN,NaN,NaN,مشاور املاک,۱۱۵ متری/شمالی رو به آفتاب/اکبری,هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...,NaN,NaN,NaN

,location_latitude,location_longitude,location_radius,regular_person_capacity,cost_per_extra_person
count,655608.000000,655608.000000,339699.000000,29870.000000,1.024100e+04
mean,34.982108,51.629743,465.149147,6.557650,1.209785e+10
std,2.379169,3.160920,125.896250,7.698655,1.103482e+12
min,23.626478,40.162369,0.000000,1.000000,0.000000e+00
25%,34.553551,50.677175,500.000000,3.000000,5.000000e+04
50%,35.723312,51.345791,500.000000,4.000000,1.000000e+05
75%,36.307013,51.805291,500.000000,7.000000,2.000000e+05
max,40.358055,74.511620,500.000000,50.000000,1.111111e+14

In [9]:
# Iran location
lat_min, lat_max = 25.06, 39.78
lon_min, lon_max = 44.03, 63.32


mask = ((my_df['location_latitude'] < lat_min) | (my_df['location_latitude'] > lat_max) |(my_df['location_longitude'] < lon_min) | (my_df['location_longitude'] > lon_max))
my_df.loc[mask, ['location_latitude', 'location_longitude']] = np.nan


neighborhood_medians = my_df.groupby(['city_slug', 'neighborhood_slug'])[['location_latitude', 'location_longitude']].transform('median')

my_df['location_latitude'] = my_df['location_latitude'].fillna(neighborhood_medians['location_latitude'])
my_df['location_longitude'] = my_df['location_longitude'].fillna(neighborhood_medians['location_longitude'])

city_medians = my_df.groupby('city_slug')[['location_latitude', 'location_longitude']].transform('median')

my_df['location_latitude'] = my_df['location_latitude'].fillna(city_medians['location_latitude'])
my_df['location_longitude'] = my_df['location_longitude'].fillna(city_medians['location_longitude'])



cols_to_drop = ['cost_per_extra_person', 'extra_person_capacity', 'regular_person_capacity', 'property_type', 'location_radius', 'neighborhood_slug']

missing_percentage = my_df.isnull().mean() * 100
display(missing_percentage.round(2))
my_df = my_df.drop(cols_to_drop, axis = 1)
display(my_df.head())

cat2_slug                   0.00
cat3_slug                   0.00
city_slug                   0.00
neighborhood_slug          56.29
created_at_month            0.00
location_latitude           0.00
location_longitude          0.00
location_radius            66.03
property_type              97.29
user_type                  71.11
title                       0.01
description                 0.00
regular_person_capacity    97.01
extra_person_capacity      97.60
cost_per_extra_person      98.98
dtype: float64

,cat2_slug,cat3_slug,city_slug,created_at_month,location_latitude,location_longitude,user_type,title,description
0,temporary-rent,villa,karaj,2024-08-01 00:00:00,35.811684,50.936600,مشاور املاک,باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه,۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...
1,residential-sell,apartment-sell,tehran,2024-05-01 00:00:00,35.773281,51.442539,مشاور املاک,۶۰ متر قلهک فول امکانات,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...
2,residential-rent,apartment-rent,tehran,2024-10-01 00:00:00,35.703865,51.373459,NaN,آپارتمان ۳ خوابه ۱۳۲ متر,تخلیه پایان ماه
3,commercial-rent,office-rent,tehran,2024-06-01 00:00:00,35.791073,51.426540,NaN,فرشته ۹۰ متر دفتر کار مدرن موقعیت اداری,فرشته تاپ لوکیشن\n۹۰ متر موقعیت اداری\nیک اتاق...
4,residential-sell,apartment-sell,mashhad,2024-05-01 00:00:00,36.271727,59.599192,مشاور املاک,۱۱۵ متری/شمالی رو به آفتاب/اکبری,هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...

In [10]:
my_df['created_at_dt'] = pd.to_datetime(my_df['created_at_month'])

min_date = my_df['created_at_dt'].min()
my_df['days_since_start'] = (my_df['created_at_dt'] - min_date).dt.days

my_df['month'] = my_df['created_at_dt'].dt.month

my_df['month_sin'] = np.sin(2 * np.pi * my_df['month'] / 12)
my_df['month_cos'] = np.cos(2 * np.pi * my_df['month'] / 12)


my_df.drop(columns=['created_at_month', 'created_at_dt'], inplace=True)


city_freq = my_df['city_slug'].value_counts()
my_df['city_freq_enc'] = my_df['city_slug'].map(city_freq)

print("cat2_slug :")
print(df['cat2_slug'].value_counts(dropna=False))
print("Number of unique categories in cat2_slug :", df['cat2_slug'].nunique())

print("cat3_slug : ")
print(df['cat3_slug'].value_counts(dropna=False))
print("Number of unique categories in cat3_slug :", df['cat3_slug'].nunique())

my_df['cat3_slug'] = my_df['cat3_slug'].fillna('unknown')
my_df['cat2_slug'] = my_df['cat2_slug'].fillna('unknown')

def extract_deal_type(cat2):
    if 'sell' in cat2:
        return 'sell'
    elif 'temporary' in cat2:
        return 'temporary_rent'
    elif 'rent' in cat2:
        return 'rent'
    else:
        return 'other'

my_df['deal_type'] = my_df['cat2_slug'].apply(extract_deal_type)

def extract_property_category(cat3):
    if 'apartment' in cat3 or 'suite' in cat3:
        return 'apartment'
    elif 'house-villa' in cat3:
        return 'villa'
    elif 'plot-old' in cat3:
        return 'plot_land'
    elif 'shop' in cat3:
        return 'shop'
    elif 'office' in cat3:
        return 'office'
    elif 'services' in cat3:
        return 'services'
    else:
        return 'other'

my_df['property_category'] = my_df['cat3_slug'].apply(extract_property_category)

cols_need_encoding = ['deal_type', 'property_category', 'user_type']

my_df_encoded = pd.get_dummies(my_df, columns=cols_need_encoding, dtype=int)
my_df_encoded.drop(columns=['cat2_slug', 'cat3_slug'], inplace=True)
print(my_df_encoded.shape)
display(my_df_encoded.head(3))

cat2_slug :
cat2_slug
residential-sell        558708
residential-rent        276558
commercial-rent          76567
commercial-sell          38861
temporary-rent           29903
real-estate-services     19403
Name: count, dtype: int64
Number of unique categories in cat2_slug : 6
cat3_slug :
cat3_slug
apartment-sell                        303385
apartment-rent                        211880
plot-old                              133570
house-villa-sell                      121753
house-villa-rent                       64678
shop-rent                              45993
shop-sell                              21855
office-rent                            21418
suite-apartment                        16465
presell                                15781
villa                                  12899
industry-agriculture-business-sell     11851
industry-agriculture-business-rent      9155
office-sell                             5155
partnership                             3622
workspace                                539
NaN                                        1
Name: count, dtype: int64
Number of unique categories in cat3_slug : 16
(1000000, 22)

,city_slug,location_latitude,location_longitude,title,description,days_since_start,month,month_sin,month_cos,city_freq_enc,...,deal_type_sell,deal_type_temporary_rent,property_category_apartment,property_category_office,property_category_other,property_category_plot_land,property_category_shop,property_category_villa,user_type_شخصی,user_type_مشاور املاک
0,karaj,35.811684,50.936600,باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه,۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...,1643,8,-0.866025,-0.500000,49367.0,...,0,1,0,0,1,0,0,0,0,1
1,tehran,35.773281,51.442539,۶۰ متر قلهک فول امکانات,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...,1551,5,0.500000,-0.866025,190904.0,...,1,0,1,0,0,0,0,0,0,1
2,tehran,35.703865,51.373459,آپارتمان ۳ خوابه ۱۳۲ متر,تخلیه پایان ماه,1704,10,-0.866025,0.500000,190904.0,...,0,0,1,0,0,0,0,0,0,0