In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import os

In [2]:
base_dir = r'C:\Users\Ramtin\Desktop\uni\quera Ai\divar-real-estate-analysis'
input_path = os.path.join(base_dir, 'preprocessing_output_v1.parquet')
df = pd.read_parquet(input_path, engine='pyarrow')
display(df.head(15))
display(df.info())
display(df.describe())

,Unnamed: 0,cat2_slug,cat3_slug,city_slug,neighborhood_slug,created_at_month,user_type,description,title,rent_mode,...,is_full_mortgage,equivalent_full_credit,weekend_price_ratio,special_day_price_ratio,is_rent_credit_convertible,allows_single_tenant,log_price_value,log_credit_value,log_rent_value,log_equivalent_full_credit
0,0,temporary-rent,villa,karaj,mehrshahr,2024-08-01 00:00:00,مشاور املاک,۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...,باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه,<NA>,...,False,NaN,2.333333,2333.333333,0,0,NaN,NaN,NaN,NaN
1,1,residential-sell,apartment-sell,tehran,gholhak,2024-05-01 00:00:00,مشاور املاک,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...,۶۰ متر قلهک فول امکانات,<NA>,...,False,NaN,NaN,NaN,0,0,22.863332,NaN,NaN,NaN
2,2,residential-rent,apartment-rent,tehran,tohid,2024-10-01 00:00:00,<NA>,تخلیه پایان ماه,آپارتمان ۳ خوابه ۱۳۲ متر,مقطوع,...,False,1.616667e+09,NaN,NaN,0,0,NaN,20.435584,17.073607,21.203632
3,3,commercial-rent,office-rent,tehran,elahiyeh,2024-06-01 00:00:00,<NA>,فرشته تاپ لوکیشن\n۹۰ متر موقعیت اداری\nیک اتاق...,فرشته ۹۰ متر دفتر کار مدرن موقعیت اداری,مقطوع,...,False,4.116667e+09,NaN,NaN,0,0,NaN,20.671973,18.369387,22.138310
4,4,residential-sell,apartment-sell,mashhad,emamreza,2024-05-01 00:00:00,مشاور املاک,هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...,۱۱۵ متری/شمالی رو به آفتاب/اکبری,<NA>,...,False,NaN,NaN,NaN,0,0,22.472466,NaN,NaN,NaN
5,5,residential-rent,apartment-rent,ahvaz,mellirah,2024-09-01 00:00:00,<NA>,اپارتمان ۱۰۰متری واحد جلو دارای دو اتاق خواب ک...,اپارتمان ۱۰۰متری ملی راه واحد جلو,مقطوع,...,False,4.500000e+08,NaN,NaN,0,0,NaN,19.336971,15.607270,19.924758
6,6,commercial-rent,office-rent,kermanshah,<NA>,2024-11-01 00:00:00,<NA>,♦مشاورین املاک سیب♦\n✅️کد:G۱۰۵\n♦با سالها سابق...,واحداداری ۸۰متری ۲۲بهمن(برق),مقطوع,...,False,6.833333e+08,NaN,NaN,0,0,NaN,18.826146,16.588099,20.342493
7,7,residential-sell,apartment-sell,tehran,dardasht,2024-09-01 00:00:00,مشاور املاک,♡♡♡♡♡♡بنام خدا♡♡♡♡♡♡\n♡♡♡عرض ادب واحترام♡♡♡\n♡...,اپارتمان ۱۰۰متری طبقه۳و۴ فول دردشت شمالی,<NA>,...,False,NaN,NaN,NaN,0,0,22.886589,NaN,NaN,NaN
8,8,residential-sell,apartment-sell,mahdasht-city,<NA>,2024-06-01 00:00:00,مشاور املاک,با سلام\n\nاملاک بزرگ اتحاد با ۲شعبه فعال با ف...,۷۸متری دوبحرنورگیر بازسازی شده شیک سندتک برگ,<NA>,...,False,NaN,NaN,NaN,0,0,20.292483,NaN,NaN,NaN
9,9,residential-sell,apartment-sell,mashhad,faramarzabbasi,2024-10-01 00:00:00,<NA>,اول رسالت فرد نزدیک به حاشیه فرامرز .. ساکنین...,متراژ ۸۰ متر فرامرز نزدیک حاشیه,<NA>,...,False,NaN,NaN,NaN,0,0,21.821878,NaN,NaN,NaN
10,10,residential-sell,apartment-sell,pardis-city,<NA>,2024-11-01 00:00:00,<NA>,سردرب عالی \nویو عالی بدون مشرف \nنصبیات نصب ش...,فاز ۱۱ زون ۲ ساخت شرکت کوزو ترکیه,<NA>,...,False,NaN,NaN,NaN,0,0,21.678777,NaN,NaN,NaN
11,11,residential-rent,apartment-rent,tehran,gisha,2024-08-01 00:00:00,مشاور املاک,‼️‼️ارزنده ترین واحد منطقه ‼️‼️ \n\n✅ 91 متر ب...,گیشا / ۹۱ متر /فرعی زوج مشرف به پارک گفتگو/ ار...,مجانی,...,True,1.200000e+09,NaN,NaN,1,0,NaN,20.905587,0.000000,20.905587
12,12,residential-sell,apartment-sell,mashhad,farhang,2024-06-01 00:00:00,<NA>,با سلام\n\n✨✨ شما لایق بهترین ها هستید ✨✨\n\n✅...,تاپ لوکیشن جلال سروش ۱۶۹متر کلید موجود قبل فرهنگ,<NA>,...,False,NaN,NaN,NaN,0,0,23.287446,NaN,NaN,NaN
13,13,commercial-sell,shop-sell,foolad-shahr,<NA>,2024-07-01 00:00:00,<NA>,مغازه فروشی بازار هنر 16متر پاخور عالی,مغازه ب8بازار,<NA>,...,False,NaN,NaN,NaN,0,0,20.560747,NaN,NaN,NaN
14,14,residential-sell,plot-old,ahvaz,pardis-ahvaz,2024-07-01 00:00:00,<NA>,یک زمین به متراژ۵۰۰متر واقع کوی سادات خیابان چ...,زمین۵۰۰ متر,<NA>,...,False,NaN,NaN,NaN,0,0,20.500122,NaN,NaN,NaN

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 63 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   Unnamed: 0                  1000000 non-null  int64
 1   cat2_slug                   1000000 non-null  string
 2   cat3_slug                   999999 non-null   string
 3   city_slug                   999998 non-null   string
 4   neighborhood_slug           437139 non-null   string
 5   created_at_month            1000000 non-null  string
 6   user_type                   288882 non-null   string
 7   description                 1000000 non-null  string
 8   title                       999946 non-null   string
 9   rent_mode                   352994 non-null   string
 10  rent_value                  350833 non-null   float64
 11  price_mode                  573606 non-null   string
 12  price_value                 555160 non-null   float64
 13  credit_mode                 352994 non-null   string
 14  credit_value                348986 non-null   float64
 15  land_size                   186396 non-null   float64
 16  building_size               980394 non-null   float64
 17  deed_type                   253458 non-null   string
 18  has_business_deed           34679 non-null    string
 19  floor                       541748 non-null   string
 20  rooms_count                 845899 non-null   string
 21  total_floors_count          304352 non-null   string
 22  unit_per_floor              302283 non-null   string
 23  has_balcony                 506411 non-null   string
 24  has_elevator                541749 non-null   string
 25  has_warehouse               728155 non-null   string
 26  has_parking                 728156 non-null   string
 27  construction_year           815828 non-null   string
 28  is_rebuilt                  529470 non-null   string
 29  has_water                   33444 non-null    string
 30  has_warm_water_provider     379500 non-null   string
 31  has_electricity             33445 non-null    string
 32  has_gas                     33430 non-null    string
 33  has_heating_system          368969 non-null   string
 34  has_cooling_system          350619 non-null   string
 35  has_restroom                406913 non-null   string
 36  has_security_guard          31312 non-null    string
 37  has_barbecue                31198 non-null    string
 38  building_direction          323923 non-null   string
 39  has_pool                    29390 non-null    string
 40  has_jacuzzi                 28728 non-null    string
 41  has_sauna                   28479 non-null    string
 42  floor_material              405984 non-null   string
 43  property_type               27057 non-null    string
 44  regular_person_capacity     29870 non-null    float64
 45  extra_person_capacity       24009 non-null    string
 46  cost_per_extra_person       10241 non-null    float64
 47  location_latitude           655608 non-null   float64
 48  location_longitude          655608 non-null   float64
 49  location_radius             339699 non-null   float64
 50  deal_type                   1000000 non-null  string
 51  is_negotiable               1000000 non-null  bool
 52  is_transformable            1000000 non-null  bool
 53  is_full_mortgage            1000000 non-null  bool
 54  equivalent_full_credit      347712 non-null   float64
 55  weekend_price_ratio         13251 non-null    float64
 56  special_day_price_ratio     10196 non-null    float64
 57  is_rent_credit_convertible  1000000 non-null  int32
 58  allows_single_tenant        1000000 non-null  int32
 59  log_price_value             555160 non-null   float64
 60  log_credit_value            348986 non-null   float64
 61  log_rent_value              350833 non-null   float64
 62  log_equivalent_full_credit  347712 non-null   float64
dtypes: bool(3), float64(17), int32(2), int64(1), string(40)
memory usage: 1.1 GB

None

,Unnamed: 0,rent_value,price_value,credit_value,land_size,building_size,regular_person_capacity,cost_per_extra_person,location_latitude,location_longitude,location_radius,equivalent_full_credit,weekend_price_ratio,special_day_price_ratio,is_rent_credit_convertible,allows_single_tenant,log_price_value,log_credit_value,log_rent_value,log_equivalent_full_credit
count,1000000.000000,3.508330e+05,5.551600e+05,3.489860e+05,1.863960e+05,9.803940e+05,29870.000000,1.024100e+04,655608.000000,655608.000000,339699.000000,3.477120e+05,1.325100e+04,1.019600e+04,1000000.000000,1000000.000000,555160.000000,348986.000000,350833.000000,347712.000000
mean,499999.500000,1.786477e+07,9.565501e+09,5.984612e+08,4.165480e+03,4.440648e+03,6.557650,1.209785e+10,34.982108,51.629743,465.149147,1.165221e+09,5.050518e+07,1.589464e+04,0.026424,0.000018,21.816745,19.193818,12.867368,20.066476
std,288675.278932,1.292364e+08,1.156717e+11,3.964895e+09,1.218927e+05,1.367118e+05,7.698655,1.103482e+12,2.379169,3.160920,125.896250,5.837942e+09,5.798675e+09,1.572101e+06,0.160393,0.004243,1.238212,1.443149,6.018968,1.126003
min,0.000000,0.000000e+00,1.000000e+07,1.000000e+00,1.000000e+00,1.000000e+00,1.000000,0.000000e+00,23.626478,40.162369,0.000000,3.433333e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,16.118096,0.693147,0.000000,3.564827
25%,249999.750000,1.111110e+05,1.500000e+09,1.000000e+08,1.100000e+02,7.500000e+01,3.000000,5.000000e+04,34.553551,50.677175,500.000000,2.800000e+08,1.086957e+00,1.111111e+00,0.000000,0.000000,21.128731,18.420681,11.618294,19.450300
50%,499999.500000,5.000000e+06,2.920000e+09,2.500000e+08,1.950000e+02,1.030000e+02,4.000000,1.000000e+05,35.723312,51.345791,500.000000,4.933333e+08,1.250000e+00,1.400000e+00,0.000000,0.000000,21.794849,19.336971,15.424949,20.016696
75%,749999.250000,1.200000e+07,6.000000e+09,5.000000e+08,2.800000e+02,1.650000e+02,7.000000,2.000000e+05,36.307013,51.805291,500.000000,9.533333e+08,1.428571e+00,1.750000e+00,0.000000,0.000000,22.515025,20.030119,16.300417,20.675475
max,999999.000000,1.000000e+10,1.000000e+13,5.000000e+11,1.000000e+07,1.000000e+07,50.000000,1.111111e+14,40.358055,74.511620,500.000000,5.017667e+11,6.675010e+11,1.587302e+08,1.000000,1.000000,29.933606,26.937874,23.025851,26.941401

In [3]:
my_columns = ['cat2_slug', 'cat3_slug', 'city_slug', 'neighborhood_slug', 'created_at_month', 'location_latitude', 'location_longitude', 'location_radius', 'property_type', 'user_type', 'title', 'description', 'regular_person_capacity', 'extra_person_capacity', 'cost_per_extra_person']
my_df = df.copy()
print(f"Number of rows : {my_df.shape[0]:,} | Number of columns : {my_df.shape[1]}")
print('Missing values % :')
missing_percentage = my_df[my_columns].isnull().mean() * 100
print(missing_percentage.round(2))
display(my_df[my_columns].head())
display(my_df[my_columns].describe())

Number of rows : 1,000,000 | Number of columns : 63
Missing values % :
cat2_slug                   0.00
cat3_slug                   0.00
city_slug                   0.00
neighborhood_slug          56.29
created_at_month            0.00
location_latitude          34.44
location_longitude         34.44
location_radius            66.03
property_type              97.29
user_type                  71.11
title                       0.01
description                 0.00
regular_person_capacity    97.01
extra_person_capacity      97.60
cost_per_extra_person      98.98
dtype: float64

,cat2_slug,cat3_slug,city_slug,neighborhood_slug,created_at_month,location_latitude,location_longitude,location_radius,property_type,user_type,title,description,regular_person_capacity,extra_person_capacity,cost_per_extra_person
0,temporary-rent,villa,karaj,mehrshahr,2024-08-01 00:00:00,35.811684,50.936600,500.0,<NA>,مشاور املاک,باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه,۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...,4.0,6,350000.0
1,residential-sell,apartment-sell,tehran,gholhak,2024-05-01 00:00:00,NaN,NaN,500.0,<NA>,مشاور املاک,۶۰ متر قلهک فول امکانات,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...,NaN,<NA>,NaN
2,residential-rent,apartment-rent,tehran,tohid,2024-10-01 00:00:00,35.703865,51.373459,NaN,<NA>,<NA>,آپارتمان ۳ خوابه ۱۳۲ متر,تخلیه پایان ماه,NaN,<NA>,NaN
3,commercial-rent,office-rent,tehran,elahiyeh,2024-06-01 00:00:00,NaN,NaN,NaN,<NA>,<NA>,فرشته ۹۰ متر دفتر کار مدرن موقعیت اداری,فرشته تاپ لوکیشن\n۹۰ متر موقعیت اداری\nیک اتاق...,NaN,<NA>,NaN
4,residential-sell,apartment-sell,mashhad,emamreza,2024-05-01 00:00:00,NaN,NaN,NaN,<NA>,مشاور املاک,۱۱۵ متری/شمالی رو به آفتاب/اکبری,هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...,NaN,<NA>,NaN

,location_latitude,location_longitude,location_radius,regular_person_capacity,cost_per_extra_person
count,655608.000000,655608.000000,339699.000000,29870.000000,1.024100e+04
mean,34.982108,51.629743,465.149147,6.557650,1.209785e+10
std,2.379169,3.160920,125.896250,7.698655,1.103482e+12
min,23.626478,40.162369,0.000000,1.000000,0.000000e+00
25%,34.553551,50.677175,500.000000,3.000000,5.000000e+04
50%,35.723312,51.345791,500.000000,4.000000,1.000000e+05
75%,36.307013,51.805291,500.000000,7.000000,2.000000e+05
max,40.358055,74.511620,500.000000,50.000000,1.111111e+14

In [4]:
# Iran location
lat_min, lat_max = 25.06, 39.78
lon_min, lon_max = 44.03, 63.32


mask = ((my_df['location_latitude'] < lat_min) | (my_df['location_latitude'] > lat_max) |(my_df['location_longitude'] < lon_min) | (my_df['location_longitude'] > lon_max))
my_df.loc[mask, ['location_latitude', 'location_longitude']] = np.nan


neighborhood_medians = my_df.groupby(['city_slug', 'neighborhood_slug'])[['location_latitude', 'location_longitude']].transform('median')

my_df['location_latitude'] = my_df['location_latitude'].fillna(neighborhood_medians['location_latitude'])
my_df['location_longitude'] = my_df['location_longitude'].fillna(neighborhood_medians['location_longitude'])

city_medians = my_df.groupby('city_slug')[['location_latitude', 'location_longitude']].transform('median')

my_df['location_latitude'] = my_df['location_latitude'].fillna(city_medians['location_latitude'])
my_df['location_longitude'] = my_df['location_longitude'].fillna(city_medians['location_longitude'])



cols_to_drop = ['cost_per_extra_person', 'extra_person_capacity', 'regular_person_capacity', 'property_type', 'location_radius', 'neighborhood_slug']

missing_percentage = my_df.isnull().mean() * 100
display(missing_percentage.round(2))
my_df = my_df.drop(cols_to_drop, axis = 1)
display(my_df.head())

Unnamed: 0                     0.00
cat2_slug                      0.00
cat3_slug                      0.00
city_slug                      0.00
neighborhood_slug             56.29
                              ...
allows_single_tenant           0.00
log_price_value               44.48
log_credit_value              65.10
log_rent_value                64.92
log_equivalent_full_credit    65.23
Length: 63, dtype: float64

,Unnamed: 0,cat2_slug,cat3_slug,city_slug,created_at_month,user_type,description,title,rent_mode,rent_value,...,is_full_mortgage,equivalent_full_credit,weekend_price_ratio,special_day_price_ratio,is_rent_credit_convertible,allows_single_tenant,log_price_value,log_credit_value,log_rent_value,log_equivalent_full_credit
0,0,temporary-rent,villa,karaj,2024-08-01 00:00:00,مشاور املاک,۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...,باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه,<NA>,NaN,...,False,NaN,2.333333,2333.333333,0,0,NaN,NaN,NaN,NaN
1,1,residential-sell,apartment-sell,tehran,2024-05-01 00:00:00,مشاور املاک,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...,۶۰ متر قلهک فول امکانات,<NA>,NaN,...,False,NaN,NaN,NaN,0,0,22.863332,NaN,NaN,NaN
2,2,residential-rent,apartment-rent,tehran,2024-10-01 00:00:00,<NA>,تخلیه پایان ماه,آپارتمان ۳ خوابه ۱۳۲ متر,مقطوع,26000000.0,...,False,1.616667e+09,NaN,NaN,0,0,NaN,20.435584,17.073607,21.203632
3,3,commercial-rent,office-rent,tehran,2024-06-01 00:00:00,<NA>,فرشته تاپ لوکیشن\n۹۰ متر موقعیت اداری\nیک اتاق...,فرشته ۹۰ متر دفتر کار مدرن موقعیت اداری,مقطوع,95000000.0,...,False,4.116667e+09,NaN,NaN,0,0,NaN,20.671973,18.369387,22.138310
4,4,residential-sell,apartment-sell,mashhad,2024-05-01 00:00:00,مشاور املاک,هلدینگ ساختمانی اکبری\n\nهمراه شما هستیم برای ...,۱۱۵ متری/شمالی رو به آفتاب/اکبری,<NA>,NaN,...,False,NaN,NaN,NaN,0,0,22.472466,NaN,NaN,NaN

In [5]:
my_df['created_at_dt'] = pd.to_datetime(my_df['created_at_month'])

min_date = my_df['created_at_dt'].min()
print(min_date)
fixed_min_date = pd.Timestamp('2020-01-01 00:00:00')

my_df['days_since_start'] = (my_df['created_at_dt'] - fixed_min_date).dt.days

my_df['month'] = my_df['created_at_dt'].dt.month

my_df['month_sin'] = np.sin(2 * np.pi * my_df['month'] / 12)
my_df['month_cos'] = np.cos(2 * np.pi * my_df['month'] / 12)


my_df.drop(columns=['created_at_month', 'created_at_dt'], inplace=True)


city_freq = my_df['city_slug'].value_counts()
my_df['city_freq_enc'] = my_df['city_slug'].map(city_freq)

print("cat2_slug :")
print(df['cat2_slug'].value_counts(dropna=False))
print("Number of unique categories in cat2_slug :", df['cat2_slug'].nunique())

print("cat3_slug : ")
print(df['cat3_slug'].value_counts(dropna=False))
display("Number of unique categories in cat3_slug :", df['cat3_slug'].nunique())

my_df['cat3_slug'] = my_df['cat3_slug'].fillna('unknown')
my_df['cat2_slug'] = my_df['cat2_slug'].fillna('unknown')

def extract_deal_type(cat2):
    if 'sell' in cat2:
        return 'sell'
    elif 'temporary' in cat2:
        return 'temporary_rent'
    elif 'rent' in cat2:
        return 'rent'
    else:
        return 'other'

my_df['deal_type'] = my_df['cat2_slug'].apply(extract_deal_type)

def extract_property_category(cat3):
    if 'apartment' in cat3 or 'suite' in cat3:
        return 'apartment'
    elif 'villa' in cat3:
        return 'villa'
    elif 'plot-old' in cat3:
        return 'plot_land'
    elif 'shop' in cat3:
        return 'shop'
    elif 'office' in cat3:
        return 'office'
    elif 'industry' in cat3:
        return 'industry'
    else:
        return 'other'

my_df['property_category'] = my_df['cat3_slug'].apply(extract_property_category)
print(my_df['property_category'].value_counts())
cols_need_encoding = ['deal_type', 'property_category', 'user_type']

my_df_encoded = pd.get_dummies(my_df, columns=cols_need_encoding, dtype=int)
my_df_encoded.drop(columns=['cat2_slug', 'cat3_slug'], inplace=True)
print(my_df_encoded.shape)
display(my_df_encoded.head(3))

2020-02-01 00:00:00
cat2_slug :
cat2_slug
residential-sell        558708
residential-rent        276558
commercial-rent          76567
commercial-sell          38861
temporary-rent           29903
real-estate-services     19403
Name: count, dtype: int64[pyarrow]
Number of unique categories in cat2_slug : 6
cat3_slug :
cat3_slug
apartment-sell                        303385
apartment-rent                        211880
plot-old                              133570
house-villa-sell                      121753
house-villa-rent                       64678
shop-rent                              45993
shop-sell                              21855
office-rent                            21418
suite-apartment                        16465
presell                                15781
villa                                  12899
industry-agriculture-business-sell     11851
industry-agriculture-business-rent      9155
office-sell                             5155
partnership                             3622
workspace                                539
<NA>                                       1
Name: count, dtype: int64[pyarrow]

'Number of unique categories in cat3_slug :'

16

property_category
apartment    531730
villa        199330
plot_land    133570
shop          67848
office        26573
industry      21006
other         19943
Name: count, dtype: int64
(1000000, 70)

,Unnamed: 0,city_slug,description,title,rent_mode,rent_value,price_mode,price_value,credit_mode,credit_value,...,deal_type_temporary_rent,property_category_apartment,property_category_industry,property_category_office,property_category_other,property_category_plot_land,property_category_shop,property_category_villa,user_type_شخصی,user_type_مشاور املاک
0,0,karaj,۵۰۰متر\n۲۰۰متر بنا دوبلکس\n۳خواب\nاستخر آبگرم ...,باغ ویلا اجاره روزانه استخر داخل لشکرآباد سهیلیه,<NA>,NaN,<NA>,NaN,<NA>,NaN,...,1,0,0,0,0,0,0,1,0,1
1,1,tehran,دسترسی عالی به مترو و شریعتی \nمشاعات تمیز \nب...,۶۰ متر قلهک فول امکانات,<NA>,NaN,مقطوع,8.500000e+09,<NA>,NaN,...,0,1,0,0,0,0,0,0,0,1
2,2,tehran,تخلیه پایان ماه,آپارتمان ۳ خوابه ۱۳۲ متر,مقطوع,26000000.0,<NA>,NaN,مقطوع,750000000.0,...,0,1,0,0,0,0,0,0,0,0

In [6]:
output_path = os.path.join(base_dir, 'preprocessing_output_v2.parquet')

my_df_encoded.to_parquet(
    output_path, 
    engine='pyarrow', 
    compression='snappy', 
    index=False 
)